# Generated by Django 2.0.7 on 2020-05-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('createdDate', models.DateField()),
                ('uuidNumber', models.UUIDField()),
                ('images', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
